### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by poberwong** [wangdicoder/JueJinClient#1]
代码如果能用一些 像 Redux 等的结构，会对后期的开发产生很大的好处...... 
页面写的非常棒，本来想帮你一起 完善项目，但因为没有一个清晰的架构体系，
可能会导致后期开发无法进行下去，或者遇到一些难以逾越的鸿沟导致代码越来越重.
可以看看我的这个[项目](https://github.com/Bob1993/mdcc-client)，希望对你有帮助
（本来打算和你一起维护，后来想到如果用 Redux 重构一下的话，代价可能偏大...）

**Comment by wangdicoder** [comment]
你那个项目确实不错哇，界面和F8的风格很像，很精美。
关于Redux，这项目我快写一半的时候才了解到这个，打算后面写另个项目使用这个架构。

感谢提出宝贵的意见～
