### ISSUE TITLE
react-native run-ios 报错了

### ISSUE THREAD

**Issue by Hu-liang** [wangdicoder/JueJinClient#16]
undefined is not an object (evaluating 'ViewPropTypes.style')

<unknown>
    DefaultTabBar.js:20
loadModuleImplementation
    require.js:122
<unknown>
    index.js:20
loadModuleImplementation
    require.js:122
<unknown>
    HomeFragment.js:10
loadModuleImplementation
    require.js:122
<unknown>
    TabBar.js:10
loadModuleImplementation
    require.js:122
<unknown>
    MainPage.js:8
loadModuleImplementation
    require.js:122
<unknown>
    entry.js:8
loadModuleImplementation
    require.js:122
<unknown>
    index.ios.js:9
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:58
global code
    require-0.js:1

**Comment by Murrayee** [comment]
你好，我也一样，你解决了吗

**Comment by thomasyxy** [comment]
同样报错，改了react-native-scrollable-tab-view，react-native的版本也不行

**Comment by decano-net** [comment]
我也一样，研究了好久不得解决，好郁闷。。。
<img width="375" alt="wx20170704-175541 2x" src="https://user-images.githubusercontent.com/2392072/27825430-169e27fc-60e2-11e7-9cc6-dccaa4db4827.png">

**Comment by wangdicoder** [comment]
@Hu-liang @Murrayee @thomasyxy @decano-net 我今天更新了react-native版本，你们重新拉一下版本再试试，我这边测试可以了，不过那个navigator已经depredeprecated。

**Comment by Hu-liang** [comment]
![image](https://user-images.githubusercontent.com/12908332/27940976-a61fc38e-6300-11e7-87a1-0d7c41486a15.png)

嘿 , 好像PropTypes在React被移除了 , 专门弄了一个库 , 现在又出现这问题了
