### ISSUE TITLE
Could not install the app on the device, read the error above for details. Make sure you have an Android emulator running or a device connected and have set up your Android development environment

### ISSUE THREAD

**Issue by xxxsf** [wangdicoder/JueJinClient#29]
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment

how to solve it ?

**Comment by zhangxiann** [comment]
I have the same error.

**Comment by xuyonglin222** [comment]
me too

**Comment by jiangguiwen** [comment]
I meet too

**Comment by jiangguiwen** [comment]
run the demo is no problem, but just run-android on the juejin's app will meet the error about above.
