### ISSUE TITLE
兄弟，出现闪退现象啊

### ISSUE THREAD

**Issue by AyumiKai** [wangdicoder/JueJinClient#3]
我的node版本是v.5.11.0

**Comment by wangdicoder** [comment]
@AyumiKai Hi, 你有看到报什么提示吗？比如为什么崩溃了？建议升级一下node，我的node版本是6.9.1

**Comment by AyumiKai** [comment]
是cnpm下载的问题，我直接用npm下载就可以了，谢谢

**Comment by wangdicoder** [comment]
@AyumiKai 不谢哈
